library(mise)
mise()  
rm()       
ls()       
gc()
rm(list = ls())
try(dev.off(dev.list()["RStudioGD"]),silent=TRUE)
try(dev.off(),silent=TRUE)
#install.packages("quantmod")
#install.packages("tseries")
#install.packages("fImport")
#install.packages("car")
#install.packages("WRS")
#install.packages("MASS")
#install.packages("RColorBrewer")
library(fImport)

SR <- "/Users/s3mx/Documents/Doctorado/CursoIntroducción-R/Data"  
setwd(SR)
getwd()
DF<-read.table("Cars.csv",header=TRUE,sep=",")
attach(DF)
detach(DF)

